#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role_gitleaks

- name: Check if gitleaks is already installed
  ansible.builtin.command: gitleaks version
  register: result
  failed_when: false
  changed_when: false

- name: Debug
  ansible.builtin.debug:
    msg: "gitleaks version: {{ result.stdout_lines }}"

- name: Install Gitleaks if not found
  when: result.rc != 0
  block:

    - name: Try to install Gitleaks via APT (Debian)
      ansible.builtin.apt:
        name: gitleaks
        state: present
        update_cache: true
      when: ansible_facts['os_family'] == 'Debian'

    - name: Try to install Gitleaks via YUM (RHEL)
      ansible.builtin.yum:
        name: gitleaks
        state: present
      when: ansible_facts['os_family'] == 'RedHat'

  rescue:

    - name: Get latest Gitleaks version from GitHub
      ansible.builtin.uri:
        url: https://api.github.com/repos/gitleaks/gitleaks/releases/latest
        return_content: true
      register: gitleaks_api_response

    - name: Set Gitleaks version
      ansible.builtin.set_fact:
        gitleaks_version: "{{ gitleaks_api_response.json.tag_name | regex_replace('^v', '') }}"

    - name: Set architecture fact
      ansible.builtin.set_fact:
        gitleaks_arch: "{{ 'x64' if ansible_architecture == 'x86_64' else ansible_architecture }}"

    - name: Build Gitleaks download URL
      ansible.builtin.set_fact:
      #  gitleaks_url: >-
      #    https://github.com/gitleaks/gitleaks/releases/download/v{{ gitleaks_version }}/gitleaks_{{ gitleaks_version }}_linux_{{ gitleaks_arch }}.tar.gz
        gitleaks_url: >-
           https://github.com/gitleaks/gitleaks/releases/download/v{{ gitleaks_version }}/gitleaks_{{ gitleaks_version }}_linux_{{ gitleaks_arch }}.tar.gz

    - name: Download Gitleaks tarball
      ansible.builtin.get_url:
        url: "{{ gitleaks_url }}"
        dest: /tmp/gitleaks.tar.gz
        mode: '0644'

    - name: Extract Gitleaks tarball
      ansible.builtin.unarchive:
        src: /tmp/gitleaks.tar.gz
        dest: /tmp
        remote_src: true

    - name: Install Gitleaks binary
      ansible.builtin.copy:
        src: /tmp/gitleaks
        dest: /usr/local/bin/gitleaks
        mode: '0755'
        remote_src: true
